# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/tsope/OneDrive/Documents/GitHub/HW-IP/vector_add/vadd/vadd.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_3/design_1_axi_dma_0_3.xci
# IP: The module: 'design_1_axi_dma_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tsope/OneDrive/Documents/GitHub/HW-IP/vector_add/vadd/vadd.gen/sources_1/bd/design_1/ip/design_1_axi_dma_0_3/design_1_axi_dma_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_0_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tsope/OneDrive/Documents/GitHub/HW-IP/vector_add/vadd/vadd.gen/sources_1/bd/design_1/ip/design_1_axi_dma_0_3/design_1_axi_dma_0_3_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tsope/OneDrive/Documents/GitHub/HW-IP/vector_add/vadd/vadd.gen/sources_1/bd/design_1/ip/design_1_axi_dma_0_3/design_1_axi_dma_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/tsope/OneDrive/Documents/GitHub/HW-IP/vector_add/vadd/vadd.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_3/design_1_axi_dma_0_3.xci
# IP: The module: 'design_1_axi_dma_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tsope/OneDrive/Documents/GitHub/HW-IP/vector_add/vadd/vadd.gen/sources_1/bd/design_1/ip/design_1_axi_dma_0_3/design_1_axi_dma_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tsope/OneDrive/Documents/GitHub/HW-IP/vector_add/vadd/vadd.gen/sources_1/bd/design_1/ip/design_1_axi_dma_0_3/design_1_axi_dma_0_3_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tsope/OneDrive/Documents/GitHub/HW-IP/vector_add/vadd/vadd.gen/sources_1/bd/design_1/ip/design_1_axi_dma_0_3/design_1_axi_dma_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
